// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UUIDGenerate is an autogenerated mock type for the UUIDGenerate type
type UUIDGenerate struct {
	mock.Mock
}

// NewString provides a mock function with given fields:
func (_m *UUIDGenerate) NewString() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewStringSlice provides a mock function with given fields: count
func (_m *UUIDGenerate) NewStringSlice(count int) []string {
	ret := _m.Called(count)

	var r0 []string
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
